### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by demayaa** [kadiraydinli/react-native-system-navigation-bar#14]
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'NavigationBar.fullScreen')] 
i'm use expo

**Comment by enestatli** [comment]
@demayaa is your project expo manage?

**Comment by shye0000** [comment]
Im having the same issue, and yeah, my project is in expo managed flow

**Comment by enestatli** [comment]
@shye0000 this is a native module, you have to eject from expo managed workflow to use.  More detail: https://docs.expo.dev/introduction/managed-vs-bare/

`With the managed workflow you only write JavaScript / TypeScript and Expo tools and services take care of everything else for you.`

There is an expo package for this maybe you can use [expo-navigation-bar](https://docs.expo.dev/versions/latest/sdk/navigation-bar/)

**Comment by shye0000** [comment]
> @shye0000 this is a native module, you have to eject from expo managed workflow to use. More detail: https://docs.expo.dev/introduction/managed-vs-bare/
> 
> `With the managed workflow you only write JavaScript / TypeScript and Expo tools and services take care of everything else for you.`
> 
> There is an expo package for this maybe you can use [expo-navigation-bar](https://docs.expo.dev/versions/latest/sdk/navigation-bar/)

Okay got it, thank you！

**Comment by kadiraydinli** [comment]
I am closing this issue because the issue has been resolved. If your problem persists, feel free to open it again. Thanks for the reply. @enestatli
