### ISSUE TITLE
how to toggle immersive

### ISSUE THREAD

**Issue by tsvetann** [kadiraydinli/react-native-system-navigation-bar#15]
What's the proper way to toggle immersive mode? I would only like to have immersive mode on a specific screen. navigationShow?

**Comment by kadiraydinli** [comment]
Hi, you can place the immersive mode on the screen where you want to use it, as in the example below. When you leave the screen, you can restore it with `navigationShow`.

```js
React.useEffect(() => {
  SystemNavigationBar.stickyImmersive();
  return () => {
    SystemNavigationBar.navigationShow();
  };
}, []);
```

**Comment by tsvetann** [comment]
@kadiraydinli that's exactly what I ended up doing but wanted to double check if this is the best practice. Thanks for helping
