### ISSUE TITLE
problem when used with StatusBar component

### ISSUE THREAD

**Issue by Pkcarreno** [kadiraydinli/react-native-system-navigation-bar#17]
I am using this property and it changes depending on if I have dark mode enabled

``` js
SystemNavigationBar.setNavigationColor(0xff00ff00, false);
```

when I have a `<StatusBar />` with backgroundColor and barStyle defined, my `<StatusBar />` ignore my custom barStyle and change status icons colors with that function

I have a screen that in its light mode uses a dark color at the top, when the function sets the dark icons become unreadable

I don't know if there is currently any way to handle this problem

Thank you very much for sharing this library.

**Comment by alessioemireni** [comment]
+1 same here

**Comment by kadiraydinli** [comment]
Hi guys, I did some changes to solve this problem. You can browse the new version; https://github.com/kadiraydinli/react-native-system-navigation-bar/releases/tag/v2.0.0

I am closing this issue for now, if your the problem persists, feel free to reopen the issue.
