### ISSUE TITLE
In Landscope mode, immersion does not work.

### ISSUE THREAD

**Issue by pk936** [kadiraydinli/react-native-system-navigation-bar#19]
When user changes the orientation to landscape, the navigation bar does not disappear.

It works only in portrait mode.

```
  const mode = useOrientation();

 const setImmer = async() => {
    const result = await SystemNavigationBar.immersive(); // does not work in landscape
  }

useEffect(() => {
   if(mode === 'LANDSCAPE'){
      setTimeout(setImmer, 2000 )
    }
  }, [mode]);
```

**Comment by liquidvisual** [comment]
In landscape mode, `hide` doesn't work either.

**Comment by kadiraydinli** [comment]
Hey @pk936 @liquidvisual, which Android version are you experiencing this issue on? I checked on Android 11 and 12. It works fine.

**Comment by pk936** [comment]
@kadiraydinli  Did you try my code as I mentioned ? After you rotate your device, the immersion mode should be activated after 2 seconds. automatically.

**Comment by kadiraydinli** [comment]
@pk936 Yes, I tried the same way.

https://user-images.githubusercontent.com/9320037/166108520-e0a2fd8d-1309-44a3-87cd-4db4ba8a152d.mov

**Comment by LouieTian0209** [comment]
I can confirm that `navigationHide` isn't working in landscape mode with API 30. I'm still seeing the navigation bar after calling `navigationHide` with my app that's locked in landscape mode. Upon debugging it seems that this promise is returning an error. I have the following code:
```typescript
SystemNavigationBar.navigationHide().then(res => {
	console.log('Code reached res section, ' + res);
}, err => {
	console.log('Code reached err section, ' + err);
});
```
And the output I get from the console is:
```shell
Code reached err section, TypeError: null is not an object (evaluating 'NavigationBar.navigationHide')
```

**Comment by MwareSolutons** [comment]
I want to add to this, for us its also not working on a Samsung Tablet Android 12. The bar disappears but the screen height is not adjusted there is now a grey area where the bar used to be.

**Comment by kadiraydinli** [comment]
I made changes for this issue, you can find it in the latest version.

**Comment by AlejandroAguilar99** [comment]
> I want to add to this, for us its also not working on a Samsung Tablet Android 12. The bar disappears but the screen height is not adjusted there is now a grey area where the bar used to be.

Hey! did you managed to make the grey area disappear? I'm having the same issue on Android 9

**Comment by AlejandroAguilar99** [comment]
> > > I want to add to this, for us its also not working on a Samsung Tablet Android 12. The bar disappears but the screen height is not adjusted there is now a grey area where the bar used to be.
> > 
> > 
> > Hey! did you managed to make the grey area disappear? I'm having the same issue on Android 9
> 
> Hi @AlejandroAguilar99, I have released a new version. I think it will solve your issue. Can you use the latest version and test it?

Thanks, but unfortunately it's still not working :/

**Comment by kadiraydinli** [comment]
@AlejandroAguilar99 What device are you testing? I can test mostly with Android emulators. I don't encounter this issue when I test it on emulators. Therefore, it becomes more difficult to solve the problem. I would be very grateful if you could share something like a sample snack for me. I want to test it in the same ambient conditions as I can. Thanks in advance.

**Comment by AlejandroAguilar99** [comment]
> @AlejandroAguilar99 What device are you testing? I can test mostly with Android emulators. I don't encounter this issue when I test it on emulators. Therefore, it becomes more difficult to solve the problem. I would be very grateful if you could share something like a sample snack for me. I want to test it in the same ambient conditions as I can. Thanks in advance.

Sorry for not letting you know before, the problem was the width of the component, since I assigned the window dimension instead of the screen dimension, it works perfectly now
