### ISSUE TITLE
Dark navigation bar doesn't work

### ISSUE THREAD

**Issue by Sondago** [kadiraydinli/react-native-system-navigation-bar#26]
Hi, i recently installed your library and when i want to "setNavigationColor" with "light bar" on true, buttons doesn't color in "black". I'm on react native v0.69. Can you help me please ?

**Comment by kadiraydinli** [comment]
Hi, what is the brand, model and Android version of the device you are using?

**Comment by Sondago** [comment]
I'm using an OnePlus 7 on Android 11 but i tried on some other devices and i got the same problem

**Comment by kadiraydinli** [comment]
@Sondago Can you check again with the latest version? If the problem persists, can you share sample code?

**Comment by Profex1999** [comment]
@kadiraydinli I'm having this issue too. I'm using both an Emulator with API level 29 and my own physical samsung S20+ (API level 31) .
In API level 30 setSystemUiVisibility and all related constants are deprecated in favor of  WindowInsetsController. 
I ran some tests and using this snippet it works.
```java
if (light) {
  getWindow.getDecorView()
     .getWindowInsetsController()
     .setSystemBarsAppearance(WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,
           WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS
   );

} else {
   getWindow.getDecorView().getWindowInsetsController().setSystemBarsAppearance(0,
           WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS
   );
}
```

**Comment by Sondago** [comment]
@kadiraydinli for me it's fixed thanks you very much !

**Comment by kadiraydinli** [comment]
I made changes for this issue, you can find it in the latest version.
