### ISSUE TITLE
Cannot call function. Possible Unhandled Promise Rejection (id: 0): TypeError: Cannot read property 'navigationHide' of null ?

### ISSUE THREAD

**Issue by cas8398** [kadiraydinli/react-native-system-navigation-bar#44]
![Capture_2023_03_28_22_16_25_209](https://user-images.githubusercontent.com/47025238/228285886-61369736-32f5-410a-b81c-a5435ff1cf9a.png)
![Capture_2023_03_28_22_16_59_170](https://user-images.githubusercontent.com/47025238/228285916-2387a059-675b-4951-a849-5ee2d571c793.png)
SKD 33
Windows 10, React Native 0.70.3

Can you help me?

**Comment by kadiraydinli** [comment]
Hi @cas8398, after installing the package, can you run the code below and try again? 
```
cd android && ./gradlew clean && cd ..
```

**Comment by cas8398** [comment]
it work, thanks 🙏

**Comment by RemyCTRZ** [comment]
Hi, I'm using Expo with React Native to build an app and I have the same problem, I can't try the above command because I don't have any android folder in my app
