### ISSUE TITLE
Error in Sentry: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference

### ISSUE THREAD

**Issue by nmalzieu** [kadiraydinli/react-native-system-navigation-bar#57]
### Description

In com.reactnativesystemnavigationbar.SystemNavigationBarModule in setModeStyle at line 472
I think it's because you are rejecting the promise but still moving on with the code here:
https://github.com/kadiraydinli/react-native-system-navigation-bar/blob/master/android/src/main/java/com/reactnativesystemnavigationbar/SystemNavigationBarModule.java#L519

You need to `return` after rejecting the promise like you do in many other places.
Actually there are 3 or 4 places in the code where the `return` is missing after the reject I think.

Thanks a lot!

### react-native-system-navigation-bar version

2.6.3

### React Native version

0.72.5

**Comment by HarshitMadhav** [comment]
+1 I am facing this issue as well

**Comment by HarshitMadhav** [comment]
+1 I am facing this issue as well in version 2.6.1
